# Generated by Django 5.2.5 on 2025-09-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField()),
                ('batch_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('test_name', models.CharField(max_length=100)),
                ('test_type', models.CharField(max_length=50)),
                ('test_pattern', models.CharField(max_length=50)),
                ('physics', models.TextField()),
                ('chemistry', models.TextField()),
                ('maths', models.TextField()),
            ],
        ),
    ]
